### ISSUE TITLE
Documentation for generating token is not precise

### ISSUE THREAD

**Issue by mkasztelnik** [indigo-iam/iam#111]
I'm trying to secure CMDB REST API with IAM. To do this I'm trying to learn how to generate user token and how  to secure the application. I'm trying to read the documentation to find some help. First step would be to fetch user token, second one is to secure my application (most probably it will be based on spring boot with spring security). 

1. Right now I found [this](https://indigo-dc.gitbooks.io/iam/doc/user-guide/oauth_token_exchange.html) and I'm trying to fetch token using my credentials using simply curl. Unfortunately documentation is not precise enough and does not explain where to find value for `SUBJECT_SECRET` variable.  
1. Can you point me into direction (e.g. project specific documentation) where I can find any hints how to secure REST API using token (I know that orchestrator [done it already](https://github.com/indigo-dc/orchestrator/tree/master/src/main/java/it/reply/orchestrator/config/security) but maybe you have more usefriendly tutorial/documentation how REST APIs can be secured using IAM integration?

**Comment by enricovianello** [comment]
Hi @mkasztelnik 

Starting from your point 2., you can find more info about INDIGO AAI and IAM by reading the following presentations:
- [An Introduction to INDIGO AAI](https://agenda.infn.it/getFile.py/access?contribId=12&resId=0&materialId=slides&confId=12164) - INDIGO Tutorial Days 2016.12.20
- [Tokens and secret security in INDIGO](https://agenda.indigo-datacloud.eu/getFile.py/access?sessionId=18&resId=0&materialId=0&confId=156) - All Hands Meeting @ Lisbon 2017.02.08

About securing your REST API application, you can see what CDMI server does, for example, [here](https://github.com/indigo-dc/CDMI/blob/master/src/main/java/edu/kit/scc/auth/OidcAuthenticationFilter.java). If I don't misunderstand, you have to do something similar (receive an access token, check validation and user identity from IAM endpoints).

About generate a valid access token for your user, you can use the curl that you pointed in 1.
But first of all, you have to register a client and obtain a CLIENT_ID and a CLIENT_SECRET.
Then, you can generate you token via curl as follow:

```
curl -s -u $CLIENT_ID:$CLIENT_SECRET \
  -d username=$YOUR_USERNAME \
  -d password=$YOUR_PASSWORD \
  -d grant_type=password \
  -d scope="openid profile" \
  $IAM_TOKEN_ENDPOINT
```

Use `https://iam-test.indigo-datacloud.eu/token` as token endpoint.

**Comment by mkasztelnik** [comment]
@enricovianello thank you for very useful links. 

First of all I would like to ask if this is a right channel for asking questions related to IDP? If not please point me into e.g. slack channel when I can ask more detailed questions. 

I created client, have client id, secret and registration access token. Unfortunately I'm not capable of changing grant type into password to get JWT token. I was trying password `grant_type` (according to the slides you pointed changing to password grant type should be done by privileged user - who should I contact?) and `client_credentials` (here after trying different combination with `Response Types` I success - after unclicking all `Response Types` - otherwise following error occurs `Incompatible response types requested: [client_credentials] / [token]`). Unfortunately `JWT` ticket received from `client_credentials` grant type request is not good enough to get user info using following curl:

```
curl -s -v -L -H "Authorization: Bearer $JWT" https://iam-test.indigo-datacloud.eu/userinfo
``` 
```json
{"timestamp":1492675386259,"status":403,"error":"Forbidden","exception":"org.springframework.security.access.AccessDeniedException","message":"Access is denied","path":"/userinfo"}
```

Another issue is that I cannot select `openid` scope (hmm I can select it but after clicking `Save` it is still unselected).

What is more after closing client edit page I'm not able to edit this service again using client id and registration access token (I'm able to enter client edit page for very limited period of time, next I'm not able to use the same credentials to enter client edit page: `Invalid client or registration access token.`).

Can you help me with these issues?

**Comment by enricovianello** [comment]
> First of all I would like to ask if this is a right channel for asking questions related to IDP? If not please point me into e.g. slack channel when I can ask more detailed questions.

For more detailed questions and support on IAM you can send an e-mail to our [indigo-iam-support](indigo-iam-support@lists.indigo-datacloud.eu) mailing list.

> I created client, have client id, secret and registration access token. Unfortunately I'm not capable of changing grant type into password to get JWT token. I was trying password grant_type (according to the slides you pointed changing to password grant type should be done by privileged user - who should I contact?)

We can change your grant type. Provide us the client-id by private email. 

> Another issue is that I cannot select openid scope (hmm I can select it but after clicking Save it is still unselected).

You need password grant_type to select it.

> What is more after closing client edit page I'm not able to edit this service again using client id and registration access token (I'm able to enter client edit page for very limited period of time, next I'm not able to use the same credentials to enter client edit page: Invalid client or registration access token.).

The self registration access token expires within 24 hours so I'll give you the current one, always by private email.

p.s. We've just invited you to our slack channel. As soon as you logged in, contact me @evianello.
