### ISSUE TITLE
IAM should allow disabling dynamic client registration

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#118]
Currently dynamic client registration is enabled by default for privileged users. It should
be possible to disable this feature completely with a configuration parameter.

**Comment by federicaagostini** [comment]
Closing this issue since it is already possible by configuration, see [documentation here](https://indigo-iam.github.io/v/v1.10.0/docs/reference/configuration/client-registration/#specify-who-can-register-a-client).

The open point is still issue https://github.com/indigo-iam/iam/issues/706.
