### ISSUE TITLE
Add ability to customize information returned by the /userinfo endpoint

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#131]
Currently the information returned by the userinfo endpoint cannot be
customized, but is fixed. It should be possible to give the ability to provide
code to choose which information should be returned, for instance by adding a
jar in a known place and by specifying the class to use in the configuration.

**Comment by rmiccoli** [comment]
Implemented through profiles https://indigo-iam.github.io/v/v1.8.0/docs/reference/configuration/jwt-profiles/
