### ISSUE TITLE
How to associate an X.509 certificate with an IAM account?

### ISSUE THREAD

**Issue by alahiff** [indigo-iam/iam#201]
I've seen in various presentations that it's possible to associate X.509 credentials with an IAM account, but I can't find any documentation about how to actually do this. On the dashboard on https://iam-test.indigo-datacloud.eu there is a section "X.509 certificates" but it after this it says "No certificates found". There doesn't appear to be any option to add a certificate.

**Comment by andreaceccanti** [comment]
Hi Andrew, currently X.509 authentication and certificate linking is not enabled on the iam-test.indigo-datacloud.eu instance. Of course, the x.509 authentication can be enabled. May I ask which kind of functionality you want to test?

**Comment by alahiff** [comment]
Hi Andrea, I would like to be able to deploy HPC clusters on EGI FedCloud sites for the EOSCpilot science demonstrator PROMINENCE. I've been doing this purely with Infrastructure Manager but want to move to using Orchestrator. In order to do this I think that I need access to IAM (at least that's my impression from all the demos), and IAM will presumably need access to my crendentials which can be used with EGI FedCloud.

**Comment by andreaceccanti** [comment]
Hi Andrew, actually I am not sure you will need certificate authentication at the IAM to interact with the Orchestration to trigger some deployment. In theory, any authentication method is fine (Google, SAML, username and password)

**Comment by andreaceccanti** [comment]
@alahiff  was the feedback helpful? Can this be closed?

**Comment by alahiff** [comment]
Thanks for you help, I'll close this now.
