### ISSUE TITLE
Include additional claims in ID token 

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#202]
# Include additional claims in ID token 

## Rationale

It has been reported that in some relying party integration it would be
convenient to have additional authentication information embeeded in id_token issued by the
IAM (groups, organisation_name, email) (the information is already available 
from the userinfo endpoint).

This work is split in two parts

1. Adding the ability to customize the JWT claim set that mitre will sign
at ID token creation time in the mitre library via an appropriate claim set
customization component

2. Provide an implementation of the customization component in the IAM that
   will add authn information depending on the set of scopes requested in the
   OIDC authentication flow

## MitreID changes

Add a spring component dependency to [DefaultOIDCTokenService][token-service]
that provides clients with the ability to customize the ID token claim set.

A possible interface is:

```java

public interface IDTokenClaimsEnhancer {

  void enhanceIdTokenClaims(JWTClaimSet claims, OAuth2Request request, Date
  issueTime, String sub, OAuth2AccessTokenEntity accessToken);

}
```

This enhancer is called by mitre implementation once all claims have been defined
but before bulding the final JWT.

A default implementation of the enhancer that does nothing is provided as a
MitreID component.

## IAM changes

An implementation of the enhancer that adds scope-filtered claims, relying on
the IamScopeClaimTranslationService, is implemented and tested.

Claims that should be added to the ID token:

- preferred_username
- email
- organisation_name
- groups

In the future we may consider having this list of claims configurable at the organization or client level, but we start with a fixed set.

[token-service]: https://github.com/indigo-iam/OpenID-Connect-Java-Spring-Server/blob/develop-1.3.x/openid-connect-server/src/main/java/org/mitre/openid/connect/service/impl/DefaultOIDCTokenService.java

**Comment by enricovianello** [comment]
IAM PR:
https://github.com/indigo-iam/iam/pull/207

OpenID-Connect-Java-Spring-Server PR:
https://github.com/indigo-iam/OpenID-Connect-Java-Spring-Server/pull/2
