### ISSUE TITLE
Basic server-side user and group search API 

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#217]
# Basic server-side users and group search API 

## Rationale

Currently users and group search is performed on the dashboard, filtering on
the results of calls that load the entire users and groups in the browser
memory. This approach has scalability issues.

Implement a basic users and group search API that returns paginated results.

## Filtering logic

For User, the search string argument should be looked up in:

- username
- uuid
- name 
- email

For groups, the search string argument should be looked up in:

- name

## User search API

A REST API is provided to search users at:

/iam/account/search

GET /iam/account/search

returns a paginated list of users matching the query parameters.

Parameters:
- filter: string, the string used by the search logic filter users. Can be
  empty
- Pagination parameters, as defined for the SCIM APIs; can be omitted,
  in which case a sensible default is used 

Returns:

A list of matching SCIM Users

Authorization: ROLE_ADMIN

## Group search API

A REST API is provided to search groups at:

/iam/group/search

GET /iam/group/search

returns a paginated list of groups matching the query parameters.

Parameters:
- filter: string, the string used by the search logic filter groups. Can be
  empty
- Pagination parameters, as defined for the SCIM APIs; can be omitted.
  in which case a sensible default is used.

Returns:

A list of matching SCIM Groups

Authorization: ROLE_ADMIN

**Comment by enricovianello** [comment]
Base url for IAM APIs is usually /iam/api/

Then, the endpoints will become:

/iam/api/account/search
/iam/api/group/search
