### ISSUE TITLE
Support for Identity Broker

### ISSUE THREAD

**Issue by SofianeB** [indigo-iam/iam#257]
Hi,

I am trying to connect our jupyterhub instance via keycloak to INDIGO IAM (https://iam-test.indigo-datacloud.eu/.well-known/openid-configuration). The redirection to the login/confirmation page works perfectly.
Unfortunately, I am getting cannot get access_token from server.

Did I miss something during configuration?

I created an account and then a client, exported the JSON file and upload it to keycloak.

Thank you.

Best,

Sofiane.

**Comment by andreaceccanti** [comment]
Hi Sofiane,
can you share the client_id for the client you created so that I can check the logs?

**Comment by SofianeB** [comment]
Hi Andrea, 
I don't know exactly what happened now --) but after many configuration changes, it seems that the integration is working. 

Cheers,
