### ISSUE TITLE
Token and ID Token timeouts

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-iam/iam#270]
When a new protected resource is registered, the timeouts for access/refresh tokens and for ID token are all set to 0.

**Comment by andreaceccanti** [comment]
Thanks @maricaantonacci, we'll fix this ASAP

**Comment by andreaceccanti** [comment]
After more investigation: this is not a bug, this is the expected behaviour.
A protected resource doesn't get tokens by the IAM service through OIDC/OAuth flows, it consumes tokens issued to other clients.
