### ISSUE TITLE
AUP Field Rendering HTML Style Tags

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#286]
Something I noticed when making the changes to the AUP in #284, is that the Existing User view will currently render any HTML style tags written into the AUP text field. Whilst this does at the moment allow for some rudimentary formatting (which is then not rendered to new users), it is probably best not to allow users to inject HTML as part of their AUP.

**Comment by andreaceccanti** [comment]
This is fixed now that IAM stores a URL for the AUP and not the actual AUP text
