### ISSUE TITLE
IAM should store and manage a URL pointing to the AUP document instead of the AUP text

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#287]
# Rationale

IAM supports AUP acceptance policy enforcement (#86).
In the current implementation, the AUP text is stored in the database. IAM should be more flexible and allow storing a URL pointing to the AUP document. Such approach would give deployers more flexibility on the AUP document format and presentation.

# Change plan 

## Change database persistence in support of AUP URL

The  AUP `text` field should be dropped in favour of an `url` field,
limited to 256 characters in length.

A flyway migration should remove the old text column and add a new column for the URL.

## API changes

AUP management APIs and tests should be changed to manage the AUP url instead of text.

## Dashboard changes

The dashboard and AUP sign pages should be updated to reflect the changes.

## Documentation changes

The AUP API documentation should be updated to reflect the changes.

# Progress tracking

- [x] Persistence changes
- [x] API changes
- [x] Dashboard changes
- [x] Documentation changes

**Comment by enricovianello** [comment]
Documentation changes PR:
https://github.com/indigo-iam/iam-documentation/pull/6
