### ISSUE TITLE
introspection endpoint does not return own defined scopes

### ISSUE THREAD

**Issue by zachmann** [indigo-iam/iam#295]
It is possible to register a client with scopes that are actually not supported. These are also displayed in the consent screen
![Screenshot_2019-09-12_11-34-49](https://user-images.githubusercontent.com/18414445/64772939-c541c580-d551-11e9-95d9-c635de74a391.png)
However, the issued AT does not include the made up scope.

Is this intended?
I think for clients it would be more clear that unsupported scopes give an error message or a silently dropped.

**Comment by andreaceccanti** [comment]
> is this something I can do as a normal user?
introspection will be enabled when you register protected resources. not sure if it can also be requested for clients without a manual intervention, I will check. That said, the right way to check if the scopes "proposed" by for client at registration time have been accepted is by querying the registration endpoint as shown above in this thread. 

Note that reserved scopes cannot be bound to dynamically registered clients by unprivileged users.

Closing this, thanks!
