### ISSUE TITLE
User may change registration name, email, etc when registering via SAML.

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#296]
When a user goes to register using an external SAML account, once they have authenticated with their IdP they are redirected to the registration view with fields completed as per the information received from the IdP.

However the registering user may then alter any of these fields as they desire. This means that the account the admin sees to approve has the potential to have a different name, email etc on it than the IdP describes.

Could this potentially cause issues with assurance when approving accounts? Whilst a user should be allowed to change their email, name, etc once registered it seems like it would be sensible to force the IdP asserted values for registration?

**Comment by andreaceccanti** [comment]
> Could this potentially cause issues with assurance when approving accounts?
The external authentication identifier is stored in the user record, so it's always possible to precisely identify  how the user was authenticated.

It's true that this information is not shown explicitly in the UI that is presented to the administrator when approving a request, there's room for improvement there.

> Whilst a user should be allowed to change their email, name, etc once registered it seems like it would be sensible to force the IdP asserted values for registration?

Currently IAM only requires a persistent attribute from the upstream IdP. Which one depends on configuration. The other attributes (username, email, eppn) are used to populate the registration form to make the life easier for the user applying for membership. Requiring that the user cannot change this information is equivalent to requiring that all IdPs provide that set of attributes. This would complicate integration with IdPs that only release a subset of the required information.

**Comment by norealroots** [comment]
This makes sense! Thanks for clarifying - the information not appearing in the UI is actually what prompted the discussion leading to this query.

I'll close this issue now.

**Comment by norealroots** [comment]
Reopening with a question: Would it be possible for the IdP asserted values to be shown to admins at approval times, alongside any changes the user may have made?

We are thinking of assurance cases, and at the moment should a user change the name the IdP supplies at registration it is not obvious to an admin that this has happened - whilst IAM still knows their UUID from the IdP, it doesn't show that the name isn't what the IdP said it was.

Our view is that - in most cases - we will trust the IdP more than the user, and so if the IdP has a name attached an admin should be able to make a decision whether a different name on the account is a reasonable request or not. Any changes after registration are recorded in the logs and so we can set up monitoring to verify whether name changes are reasonable, however at current this is not possible to do at registration.

**Comment by andreaceccanti** [comment]
> Would it be possible for the IdP asserted values to be shown to admins at approval times, alongside any changes the user may have made?

The dashboard can be changed to show more details about how the user was authenticated.

**Comment by norealroots** [comment]
Excellent - is that something you can currently do or something to be added? Would you like me to submit a feature request if it is to be added?

**Comment by andreaceccanti** [comment]
See #304

**Comment by andreaceccanti** [comment]
Closing as the discussion as led to the cration of #304
