### ISSUE TITLE
IAM should allow customisation of the positoning of login page UI elements

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#298]
At the moment the IAM login page has a UI with fixed elements - ie the option to sign in with IAM credentials is always the top of the list of sign-in options. It would be good if the ordering of these elements could be customised, so that an admin can decide which sign in option is the top of the list. 

This would be useful as the topmost option can be perceived as the default sign-in option, and may unintentionally discourage people from other options. 

I've attached below the current view and a quick mockup of how we would like to be able to configure it.

Current login view:
![loginCurrent](https://user-images.githubusercontent.com/22589560/65236384-625fa980-dad0-11e9-98ed-6a08d3ecd038.png)

Login view with proposed changes:
![loginMockup](https://user-images.githubusercontent.com/22589560/65236406-6c81a800-dad0-11e9-96f2-b4fc94cd22a2.png)

**Comment by andreaceccanti** [comment]
Ok, adding this to the 1.6 backlog

**Comment by andreaceccanti** [comment]
Does #330 fix this as well?
It's now possible to have a login page that looks like this:

![Screenshot 2020-06-15 08 02 15](https://user-images.githubusercontent.com/1152853/84622969-8b399180-aede-11ea-81e2-85c807470e97.png)

**Comment by rmiccoli** [comment]
Reference to code [here](https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/webapp/WEB-INF/views/iam/login.jsp#L76)
