### ISSUE TITLE
Finalize IAM 1.5.0 release

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#303]
- [x] Relase tag created
- [x] Docker image available on Dockerhub
- [x] Packages available on the new IAM package repository
- [x] Documentation updated and available on IAM documentation site

**Comment by norealroots** [comment]
Hi, do you have a planned time-frame for the Docker release of 1.5.0? Cheers!

**Comment by andreaceccanti** [comment]
HI Tom, the code is stable, the image is now on Dockerhub

https://hub.docker.com/layers/indigoiam/iam-login-service/v1.5.0.RELEASE-latest/images/sha256-b9eb53f6f265e8fa3110537543d4b37f7e383a6304392a96cfa619875d53266f
