### ISSUE TITLE
The token management API should not show registration tokens 

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#312]
IAM provides a token management API to VO admins that grants access
to user tokens to administrators.
The API currently also shows information about client and resource server registration tokens.
The API should be modified to not show such information

##  Required changes
Change the access tokens repository logic so that registration tokens are not returned in lookup queries.

**Comment by marcelovilaca** [comment]
Pull Request https://github.com/indigo-iam/iam/pull/315
