### ISSUE TITLE
All newly-registered users are sent an email to set a password, no matter which method they signed up.

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#321]
When a user's registration request is approved, they will be sent an email with a link to set a password for their account. Whilst this is the expected, and required, behaviour for local IAM accounts, it would be preferred if this could be disabled for users who register with an external IdP. This way we only keep passwords for the small subset of users who have local accounts, rather than potentially all users in the system.

**Comment by andreaceccanti** [comment]
The local password is used as a backup login solution, and to enable authn flows that would be otherwise impossible to support (e.g., the resource owner password credential flow).

**Comment by norealroots** [comment]
I understand the benefits of it, but would it be possible to have the email not automated? That way users could set a password on their account manually, should they need one?

**Comment by andreaceccanti** [comment]
Currently the flow to set the password relies on an email ownership check, and is also the mechanism to reset the password when the user forgets the password.

**Comment by norealroots** [comment]
That makes sense. My point was that the majority of our users will be authenticating using external accounts, and most (I believe) won't need to use username/password. I felt that having the option of not requesting external users to set passwords would help be clearer about preferred work flows, and potentially reduce the amount of passwords we store - and therefore reduce the security concerns associated with then.

**Comment by norealroots** [comment]
Just had a more in-depth conversation about this here and there's a few interesting scenarios involved we've just discussed:

1. If a user signs up with their eduGain account and can only access their account with said eduGain account, then we know that they can only access our service for the duration of their affiliation with the institution in question. Should they be able to add a password to their account, this is no longer the case - if their account at their institution becomes inactive, they can still access IAM with username and password.
2. As the password set email operates using the same flow as the password reset, what happens if a user ignores this email and does not set a password? It is that there would be that there would be a randomly generated initial password attached to their account, which they would not know? Would a suitable workflow be then to not send an initial password setting email, and should a user need password access they can request an admin send a new reset email?

**Comment by willfurnell** [comment]
I've been looking into this as a general 'How can we modify the emails sent to users' issue. As it looks like the configuration templates are done with Velocity, I think we should be able to get away with making a configuration option for Velocity to look on disk rather than in the .war for the files it needs - then we can modify these files.

**Comment by andreaceccanti** [comment]
Hi, I just added support for disabling local authentication (see #337 ) which I think also solves this as well.
