### ISSUE TITLE
Revised access to health endpoints for Monitoring Purposes

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#333]
The IAM has a number of health metrics available at the `/health` endpoints, however these require admin credentials for more information than just "up". If using monitoring tools including admin level credentials in repeated jobs does not feel the most secure, and so an alternative method for retrieving the metrics would be desirable - perhaps either a less-privileged monitoring account or restricted API key could be implemented?

**Comment by andreaceccanti** [comment]
Hi Tom,
IAM already provides support for access those endpoint through a dedicated account that
only grants access to actuator endpoints.

https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/resources/application.yml#L84-L85

The account env variables naming is not optimal, but that seems to be what you need.
