### ISSUE TITLE
Do not show the regexp used to validate username in "invalid user" error messages

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#387]
The current error message a user gets when they try to register an account with a username which fails to meet the Unix regex, expresses this by stating the required regex:

`Invalid registration request: invalid username (does not match with regexp for UNIX usernames: '^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}$)$') `

This is not overly user-friendly, and should be updated to be more legible to those who do not know regex. For example:

> Invalid username - does not match regex for UNIX usernames. Please ensure your username only uses lowercase letters (a-z), numbers (0-9) or underscores (_). All usernames must start with a letter and may not be longer than 31 characters.

**Comment by andreaceccanti** [comment]
Hi @norealroots,
Thanks for the bug report. Yes, the message is criptic, we'll remove the reference from the regexp, i.e. the message will be something like: 
```
Invalid registration request: invalid username ( the provided username is not a valid UNIX username)
```
