### ISSUE TITLE
wlcg.groups scope behavior does not match WLCG common profile

### ISSUE THREAD

**Issue by DrDaveD** [indigo-iam/iam#388]
Currently if I ask only for the specific group scope "wlcg.groups:/wlcg/xfers" from the IAM at https://wlcg.cloud.cnaf.infn.it/ I get back the full list of groups I am authorized for instead of just the one I asked for, specifically
```
  "wlcg.groups": [
    "/wlcg/pilots",
    "/wlcg",
    "/wlcg/xfers"
  ]
```
That's a problem for group-based authorization because I want to limit the power of the token to just a selected group.

**Comment by andreaceccanti** [comment]
IAM, when using the WLCG profile, supports two types of groups: the defaul groups, that you always get, and the optional ones, that you get only on request. All the groups you listed are default groups, i.e. they are always returned, i.e. IAM is behaving correctly. 

IAM ensures the order is consistent with what is requested (following the good old primary FQAN concept), so just be sure that the group you want to have as primary is requested as the first group and it will end up as the primary group in the list of wlcg.groups.

Example:
```
$ oidc-token -s openid -s wlcg.groups wlcg | jwt
```
```json
{
  "wlcg.ver": "1.0",
  ...,
  "wlcg.groups": [
    "/wlcg",
    "/wlcg/pilots",
    "/wlcg/xfers"
  ]
}
```
$ oidc-token -s openid -s wlcg.groups:/wlcg/pilots wlcg | jwt
```
{
  "wlcg.ver": "1.0",
  ...,
  "wlcg.groups": [
    "/wlcg/pilots",
    "/wlcg",
    "/wlcg/xfers"
  ]
}
```

**Comment by DrDaveD** [comment]
Ok, I see.  Are there any optional groups I can join on the wlcg IAM to test out the optional groups functionality?

**Comment by andreaceccanti** [comment]
The `/wlcg/test` is an optional group that you can use for testing.

**Comment by DrDaveD** [comment]
Ok I joined the group but `/wlcg/test` is not coming back when I request it.

And why is `/wlcg/pilots` a default group?  Isn't that supposed to indicate it is a token only for pilot jobs?

**Comment by DrDaveD** [comment]
Ah ok, /wlcg/test is working now that membership in the group has been confirmed.  I saw it listed after I requested it and didn't notice it was still in the "Group requests" section instead of "Groups". 

It would be helpful if the Groups list indicated whether or not a group was a default group.

**Comment by andreaceccanti** [comment]
> It would be helpful if the Groups list indicated whether or not a group was a default group.

ah, it's already so for the group listing page but not for the account dashboard home, this is a bug, thanks for reporting.
