### ISSUE TITLE
The IAM SCIM endpoint is currently not advertised in the OpenID Provider Metadata

### ISSUE THREAD

**Issue by paulmillar** [indigo-iam/iam#394]
Section 2.1 of the [OpenID Connect Profile for SCIM Services](https://openid.net/specs/openid-connect-scim-profile-1_0.html#discoveryMetadata) says that the [OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) SHOULD contain an entry `scim_endpoint` that points to the SCIM endpoint.

Currently IAM does not advertise its SCIM endpoint in this fashion, as shown below with the ESCAPE IAM instance:

```
paul@sprocket:~$ curl -s https://iam-escape.cloud.cnaf.infn.it/.well-known/openid-configuration | jq -r .scim_endpoint
null
paul@sprocket:~$ 
```

**Comment by andreaceccanti** [comment]
Hello @paulmillar, 

IAM supports SCIM and OIDC but is not yet compliant with the RFC you mentioned. In any case, we plan to be compliant eventually, so thanks for pointing this out!
