### ISSUE TITLE
IAM username update blocked by case insensitive "is username available" check

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#434]
IAM prevented updating the username for a user from `JColl` to `jcoll`.
Apparently the check that verifies whether a username is already taken is case insensitive and should be fixed.

**Comment by rmiccoli** [comment]
This should be solved by adding a DB migration in order to make the username column case sensitive:
`alter table iam_account modify username char(255) character set latin1 collate latin1_general_cs;`

Currently, the default collation is `latin1_swedish_ci`.

**Comment by enricovianello** [comment]
@giacomini suggests to do an analysis of all the columns that could needs to be case sensitive in order to do all the migrations in one time
