### ISSUE TITLE
group page navigation broken

### ISSUE THREAD

**Issue by belforte** [indigo-iam/iam#445]
see screenshot below
![Screenshot from 2021-12-14 18-27-18](https://user-images.githubusercontent.com/1837785/146049126-684897e1-9708-4fc9-ba81-5b31205bff35.png)
there are 49 groups, so I expect to be able to see the other ones using the navigation arrows at the bottom,
but hovering with the mouse shows a stop-sign icon (in screenshot it came a bit off in position) and clicking
on them is not doing anything.

**Comment by belforte** [comment]
well.. same problem also for the "simple" user list. navigation arrows are not working

**Comment by andreaceccanti** [comment]
CIao Stefano, thanks. Yes this is a known issue, with an easy workaround: click on the table headers to trigger a sorting of the records (e.g., the name column) and the paginator will work as expected. This will be fixed in the next IAM release.

**Comment by rmiccoli** [comment]
Solved in 1.8.0 release.
