### ISSUE TITLE
When attempting to access the UserInfo endpoint with a scopeless token, the user attributes are still returned as a HTML doc

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#455]
The `userinfo` endpoint should only return attributes when presented with a valid access token which contains the `openid` and `profile` scopes. However, it seems that when the endpoint is presented with a scope-less token it will demonstrate a 403 error in the access logs whilst still returning the JSON attributes wrapped in HTML formatting, as so:
```
curl -X GET -H "Authorization: Bearer ${IAM_ACCESS_TOKEN}" https://ourIAMInstance/userinfo                           

<!DOCTYPE html>
<html lang="en_US">

<head>

<base href="https://ourIAMInstance/">
<title>ourIAMInstance-An unexpected error occurred</title>

<meta charset="utf-8">
... user information below here
...
```
When attempted to access with an under-privileged token, the `userinfo` should just return the 403 error code and not the user attributes.

**Comment by rmiccoli** [comment]
In the new v1.8.0 branch, the above problem has been fixed. When you submit to the userinfo endpoint with a scope-less token, you get the following message:
```
$ curl -X GET -H "Authorization: Bearer ${BT}" http://localhost:8080/userinfo
{"error":"insufficient_scope","error_description":"Insufficient scope for this resource","scope":"openid"}
```
