### ISSUE TITLE
When a User makes changes to a client, this removes assigned SCIM scopes

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#461]
The INDIGO IAM restricts the ability for users to assign the SCIM scops to their clients, as per the service documentation here: 
> Note that these scopes are restricted in the default IAM configuration, i.e. can be assigned to clients only by IAM administrators.

However, this has the affect that should a user change their client after an admin has assigned a client the SCIM scopes, the IAM will remove them from the client. I have tested this with assistance from a service manager, and can verify that when the client settings are changed, the SCIM scopes are removed. 

The IAM should not remove SCIM scopes when a user makes client changes.

**Comment by giacomini** [comment]
Which changes were made to the client?

**Comment by norealroots** [comment]
@giacomini Apologies for the delay - whenever the client owner makes any changes, any SCIM options are reset.

**Comment by giacomini** [comment]
I can imagine reasons why a change in the client configuration requires a re-approval of the SCIM scope (e.g. a change in privacy policy), but that's certainly not true in general. We'll review the approach after the next release.

**Comment by norealroots** [comment]
Thank you! We found this when a colleague was trying to configure RUCIO as a client, and found that they had to keep asking me to fix the SCIM scopes if they made any schanges to their other options.

**Comment by enricovianello** [comment]
The upcoming release v1.8.0 won't "reset" restricted client scopes already assigned.
