### ISSUE TITLE
Incorrect Request URL in e-mail to group managers.

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#463]
The e-mail sent to group managers has an incorrect link within it. When you click `https://[IAM Base URL]/dashboard#/requests]` this will instead redirect to takes me to `https://[IAM Base URL]/dashboard#!/home`.

I think the link should be `https://[IAM Base URL]/dashboard#!/requests` (with a "!")

**Comment by rmiccoli** [comment]
Typo fixed in commit 355ed81.
