### ISSUE TITLE
Add AARC eduperson_assurance claim and scope

### ISSUE THREAD

**Issue by enricovianello** [indigo-iam/iam#468]
Following the [AARC-G021](https://aarc-community.org/wp-content/uploads/2018/02/AARC-G021-Exchange-of-specific-assurance-information-between-Infrastructures.pdf) guidelines, add the eduperson_assurance claim and related scope.

**Comment by rmiccoli** [comment]
Fixed in commit 456fc91

**Comment by enricovianello** [comment]
https://github.com/indigo-iam/iam/commit/456fc91aaa4bcbd15a781cb102c4fdf9566faa8b
