### ISSUE TITLE
Misleading userId filtering in the token management API

### ISSUE THREAD

**Issue by rizart** [indigo-iam/iam#471]
Hello,

When one queries the token management API [1], for access or refresh tokens, they can filter the results with a `userId`.
The problem is that what is described as `userId` is in essence the `user.userName` of the user and not the `user.id` field from the results, that one would expect. This can be traced for example in the following code snippets:
https://github.com/indigo-iam/iam/blob/5bf97fab616c1347ccff03e93204000b9b71cc21/iam-login-service/src/main/java/it/infn/mw/iam/persistence/repository/IamOAuthAccessTokenRepository.java#L57

https://github.com/indigo-iam/iam/blob/5bf97fab616c1347ccff03e93204000b9b71cc21/iam-login-service/src/main/java/it/infn/mw/iam/persistence/repository/IamOAuthRefreshTokenRepository.java#L49

Not sure if this is a matter of clarifying/changing the API documentation, or if some changes are needed in the code.

[1] https://indigo-iam.github.io/v/v1.7.2/docs/reference/api/tokens-api/

**Comment by federicaagostini** [comment]
Thank you, Rizart.

It is fixed now in the documentation of the incoming IAM release ([81165d7](https://github.com/indigo-iam/iam-website/commit/81165d78f836831f6befc7902b63d5ad3afce457)) but I leave the issue open if we want to change this in the code at some point.
