### ISSUE TITLE
Fix wrong message "You have notifications" when there's no notifications

### ISSUE THREAD

**Issue by enricovianello** [indigo-iam/iam#472]
![notifications-ui-error](https://user-images.githubusercontent.com/1914039/159305722-da8ec96a-7c58-488d-bf40-ac402a2b9f39.png)

**Comment by rmiccoli** [comment]
Fixed in commit 297e82d.

![notifications](https://user-images.githubusercontent.com/85555840/159471209-f09a6888-a66e-435c-b200-b246993caea8.png)

**Comment by rmiccoli** [comment]
Fixed in commit e9a6314.

![0notifications](https://user-images.githubusercontent.com/85555840/159477490-89a7f4e2-5c7e-48d4-85da-913e8b48ed15.png)

![1notification](https://user-images.githubusercontent.com/85555840/159477515-586368ef-fc0f-4f48-a510-2ec54b378285.png)
