### ISSUE TITLE
Group Manager unable to view user info, with unhelpful error message

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#475]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/22589560/160835993-aff2d86e-0861-4cca-a902-9b8f13efa97e.png)
When a Group Manager tries to click the link on a username, they get a "An Unexpected Error Occured" error message. I believe this is likely due to a Manager not being able to view a user's profile.
Would it be possible for a Manager to be able to view limited information on a user's profile, for making group decisions? And otherwise, could the error message be changed to be more helpful?

**Comment by rmiccoli** [comment]
Fixed in IAM v1.8.1
