### ISSUE TITLE
Editing first name/family name fails on the dashboard

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#49]
The dashboard invokes an SCIM patch operation, but sends an empty password, and this makes the database update fail.
1. A patch with an empty email should trigger an error **before** reaching the database (an update with an empty email should never be accepted)
2. The dashboard should send in the SCIM patch request only the fields that are actually changed by the user

**Comment by enricovianello** [comment]
Pull Request opened
https://github.com/indigo-iam/iam/pull/57
