### ISSUE TITLE
Enable smoother navigation for local accounts when IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY=hidden

### ISSUE THREAD

**Issue by jouvin** [indigo-iam/iam#515]
I was sure I already opened an issue about this... but it doesn't seem the case.

As discussed at the last [workshop](https://indico.cern.ch/event/1185598/), in most IAM instances, you generally want to discourage the use of local accounts by defining `IAM_REGISTRATION_SHOW_REGISTRATION_BUTTON_IN_LOGIN_PAGE=false` and `IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY=hidden`. This works well and doesn't prevent using local accounts for some specific needs (e.g. administrators) if adding `?sll=y` to the login page URL.

Unfortunately, the `?ssl=y` trick doesn't work well when redirected to the login page from another IAM page, like the dashboard, as it breaks the redirect URL after the successful authentication. It would be good to offer a smoother navigation for this use case, for example by adding a link at the bottom of the login page to open the local account login page without breaking the redirect URL.

**Comment by norealroots** [comment]
I'd like to second this - currently we have local login shown, so as to not break flows.

As a similar, but slightly tangential comment: would it be possible to add an "Apply for an account with eduGain" button next to the regular apply button? I know the flow would be the same as clicking the other eduGain button, but it would be more obvious from a user's point of view that this is what they should be doing.

Thanks!

**Comment by giacomini** [comment]
Ok. We need to find a way to make it very clear that these are *local* credentials, to avoid that people think that they are username/password of the CERN SSO (for example).

**Comment by federicaagostini** [comment]
PR https://github.com/indigo-iam/iam/pull/669
