### ISSUE TITLE
Add statistical endpoint

### ISSUE THREAD

**Issue by rmiccoli** [indigo-iam/iam#516]
e.g. for the number of VO users; it should be public

**Comment by vokac** [comment]
Related [GGUS:155077](https://ggus.eu/index.php?mode=ticket_info&ticket_id=155077)

**Comment by rmiccoli** [comment]
The output of the following query shows only the total number of VO users:
```
curl -H "Authorization: Bearer $AT" https://iam-dev.cloud.cnaf.infn.it/scim/Users?count=0 | jq 
{
  "totalResults": 22,
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:ListResponse"
  ],
  "Resources": []
}
```
and we can extract it like this:
```
curl -H "Authorization: Bearer $AT" https://iam-dev.cloud.cnaf.infn.it/scim/Users?count=0 | jq .totalResults
22
```

**Comment by maarten-litmaath** [comment]
Ciao Roberta,
we need something like that to work without an AT...

**Comment by giacomini** [comment]
We probably need to have a `/stats` endpoint (name to be decided) that we populate with some basic information. Based on your experience, can you give some indication on what this information can be, at least as a first solution? As a format, is JSON ok?

**Comment by maarten-litmaath** [comment]
Hi all,
while the Operations Portal may get the list of users from VOMS-Admin to count them,
we can no longer do that in these GDPR times.  The **number** of users is sufficient,
to be made available anonymously, so that we avoid hassles with client registration
and operations: _"My client no longer works: help!"_

**Comment by maarten-litmaath** [comment]
Hi again,
JSON format sounds fine.

**Comment by federicaagostini** [comment]
PR https://github.com/indigo-iam/iam/pull/790.
