### ISSUE TITLE
Notifications of group requests should only reach IAM group managers

### ISSUE THREAD

**Issue by rmiccoli** [indigo-iam/iam#521]
Currently also reach IAM administrators.

**Comment by rmiccoli** [comment]
It's already possible to send emails for group requests only to group managers by setting `IAM_NOTIFICATION_GROUP_MANAGER_NOTIFICATION_POLICY=notify-gms`. The default value is `notify-gms-and-admins`.

To be added to the documentation.

**Comment by norealroots** [comment]
Just to check - for the case of a group with no managers, would that send notifications to admins if the `notify-gms` option is chosen?

**Comment by rmiccoli** [comment]
No, actually the email is not sent to anyone and we only have a notification in the admin dashboard.

**Comment by norealroots** [comment]
That makes sense, thanks!
