### ISSUE TITLE
Rados Gateway unable to perform STS with IAM

### ISSUE THREAD

**Issue by ahmadalkhansa** [indigo-iam/iam#529]
Hi, 

I'm facing issue with using oidc provider with RadosGW when it is configured with IAM. Logs of RadosGW shows the following:

```
07T13:25:13.939+0000 7fb0e7bc8700 20 req 5791232672279210617 0.009000258s sts:assume_role_web_identity Cert URL is: https://<iam>/jwk
debug 2022-11-07T13:25:13.939+0000 7fb0e7bc8700 20 sending request to https://<iam>/jwk
....
07T13:25:13.943+0000 7fb0e6bc6700  0 req 5791232672279210617 0.013000373s sts:assume_role_web_identity x5c not present
```

This is related to jwks_uri endpoint where it looks for x5c certificate.
These keys may be also significant:
```
{
  "kid": "<kid>",
  "kty": "RSA",
  "alg": "RSA-OAEP",
  "use": "enc",
  ...
  "x5c": []
}
```

**Comment by enricovianello** [comment]
Hi @ahmadalkhansa , usually you should provide your keystore.jwks by using env variable IAM_KEY_STORE_LOCATION or via application.yaml property iam.jwk.keystore-location. As soon you provide a jwks file that includes that `x5c` field, this value will be published by your IAM endpoint. By default this field is not mandatory from spec so it's not generated.

To generate a new keystore you can use the mitreid-connect's tool named json-web-key-generator:
https://github.com/mitreid-connect/json-web-key-generator
```
git clone https://github.com/mitreid-connect/json-web-key-generator.git
cd json-web-key-generator
mvn clean package
java -jar target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar -t RSA -s 2048 -S -x
```
You can copy the generated keystore and manually add the x509 certificate as your `x5c` field (in form of array with one element).

**Comment by ahmadalkhansa** [comment]
Hi @enricovianello, thank you for your response. It worked!
