### ISSUE TITLE
CERN HR suspended status synchronization

### ISSUE THREAD

**Issue by vokac** [indigo-iam/iam#530]
It seems to me we still don't have official ticket for issue with cleaning suspended status when account gets activated in CERN HR database (if I remember correctly this was somehow related to the [endDate](https://github.com/indigo-iam/iam/blob/5bf97fab616c1347ccff03e93204000b9b71cc21/iam-login-service/src/main/java/it/infn/mw/iam/core/lifecycle/cern/CernHrLifecycleHandler.java#L176) that is set during account suspension, but not cleared during account re-activation). This is quite important defect that is already causing troubles with IAM operation.

**Comment by giacomini** [comment]
In the meantime that there is a proper fix in the code, the end date can be reset using the API. There is a [script](https://github.com/indigo-iam/iam-scripts/blob/restore_user/restore-user.sh) that we have used successfully in the past.

**Comment by vokac** [comment]
I hope this will be really fixed in next release / this should get priority, because with few thousands accounts it is not rare that membership for some user expire / they switch institutions => they get suspended for a short time in CERN HR database. In this case we have to fix these account manually...
