### ISSUE TITLE
serving the JWKS URL from a static file

### ISSUE THREAD

**Issue by maarten-litmaath** [indigo-iam/iam#539]
Because an IAM service should continue to be able to serve the **JWKS** URL also when its DB has become slow for some reason, that URL would best be served from a static file that is updated from time to time by a background process. It would very much have mitigated the IAM-ATLAS Halloween outage.

**Comment by giacomini** [comment]
This can probably be solved easily using NGINX caching features. See `proxy_cache_*` directives in https://nginx.org/en/docs/http/ngx_http_proxy_module.html.

**Comment by federicaagostini** [comment]
Closing this issue since the NGINX solution looks like the cleanest one. Feel free to reopen it in case of further discussion.
