### ISSUE TITLE
Any token created by IAM admin have full access to IAM API

### ISSUE THREAD

**Issue by vokac** [indigo-iam/iam#543]
When IAM account with ROLE_ADMIN gets token with arbitrary content (claims / scopes / audience) it still have full admin privileges on the IAM API endpoints. This is really dangerous in case people with admin privileges "accidentally" try to use their token with any other service. Two different IAM accounts (one with just ROLE_USER and second with ROLE_USER+ROLE_ADMIN) is the only way to deal with current IAM behavior, but I can see two problems with this approach

- bad design (too dangerous default behavior) for any IAM admin tokens
- multiple user accounts are complicated to manage

I think that even with ROLE_GM:group-uuid any token have special privileges on the IAM API and Group-Managers might be much bigger group of users that would need secondary account and that needs to understand security consequences of using any token issued for account with additional / privileged ROLE_*.

It would be nice if just tokens with very specific scopes or audience issued to IAM administrator could be accepted for privileged operation that requires ROLE_ADMIN, e.g. it would be much more difficult for IAM admin to "accidentally" get token with very specific `aud` set to "IAM_ADMIN_PRIVILEGED_AUDIENCE" and use it for non-IAM API operations.

**Comment by jouvin** [comment]
From the hackaton discussion: proposal is to restrict the use of admin and group manager roles to the interaction through the dashboard and require scopes when using the API. Looking at the code, it seems a minimal change that can be implement by a stricter version of the 2 functions used in annotations that check the presence of the roles so that they reject the role if an OAuth2 authentication has been tried (wether it succeeded or failed).

**Comment by rmiccoli** [comment]
Hi all, PR #562 implements this type of logic:

- in case of OAuth2Authentication (with token), access to the IAM APIs is based on the new `admin:read` and `admin:write` scopes
- in case of UsernamePasswordAuthenticationToken (through dashboard), access to the IAM APIs is only role-based

The same behaviour for the SCIM API but with the only difference that the required scopes are `scim:read` and `scim:write`.

In this way, we limit an admin's token privileges. Does that sound good?
