### ISSUE TITLE
Case sensitivity confusion between MySQL unique fields and JPA equals comparisons

### ISSUE THREAD

**Issue by enricovianello** [indigo-iam/iam#550]
Notes:
- MySQL unique columns are case-insensitive
- JAVA equals method are case sensitive

We have experienced that trying to link to a user an x509 certificate with a subjectDN that differs from one already linked in terms of some lower/upper case, this leads to a "DUPLICATE ENTRY" error at MySQL level and is not caught before by IAM logic. For the triggered IAM PATCH SCIM updater the 2 certificates are not equals, in fact.
This problem could affect also other unique columns of our database.
We have to evaluate the impact of one of the following solutions:
- make MySQL database case sensitive
- re-write JPA equals method in a case-insensitive way

**Comment by enricovianello** [comment]
The solution that we want to pursuit is making the MySQL column "subject_dn" case sensitive

**Comment by rmiccoli** [comment]
This should be solved by adding a DB migration in order to make the subject_dn column case sensitive:
alter table iam_x509_cert modify subject_dn char(255) character set latin1 collate latin1_general_cs;

Currently, the default collation is latin1_swedish_ci.

**Comment by rmiccoli** [comment]
PR #623

**Comment by enricovianello** [comment]
Linked to new PR #624
