### ISSUE TITLE
no hyperlink in case of no name

### ISSUE THREAD

**Issue by stlammel** [indigo-iam/iam#568]
Dear IAM developers,
   in case a client is registered without name, there is no hyperlink to the
clinet information page provided in the selection table. I attach a screenshot
to show the issue for client id 187fd52c-81d7-4660-add0-975758b6ff3c .
Could you take a look? (Maybe a hyperlink for the whole first field of the
client row?)
   Thnaks,
       cheers,  Stephan

![iam001](https://user-images.githubusercontent.com/5392791/218852109-5b802c04-4e4c-49c5-af21-c4b1e94a0ebc.png)

**Comment by rmiccoli** [comment]
Hi Stephan,
we can have three different options:

* add hyperlink on both client_id and client_name
![Screenshot from 2023-02-21 18-10-33](https://user-images.githubusercontent.com/85555840/220418786-3bfa405d-6703-4008-a19b-c3c414a81758.png)

* add hyperlink only on client_id
![Screenshot from 2023-02-21 18-11-23](https://user-images.githubusercontent.com/85555840/220418886-155d1715-7814-4f49-b7cc-bdac14124931.png)

* add a default name to clients created without a name (thus leaving the hyperlink only on client_name)
![Screenshot from 2023-02-21 18-30-04](https://user-images.githubusercontent.com/85555840/220418936-3a1dc3d6-93c2-40e0-b2c7-74d8b59fbac1.png)

Which one do you prefer?

**Comment by stlammel** [comment]
Hallo Roberta,
   thanks for taking a look. Either one is fine. I believe client names are not unique and the link is really via id. I would thus include the id in the hyperlink or just the id (your option 2).
   Thanks,
          cheers,  Stephan

**Comment by enricovianello** [comment]
Knowing that since IAM v1.8.0 the API won't allow to leave client name empty, we decided to fix the already created clients by adding a migration within IAM v1.8.1 (soon released) that initialize no-named clients with the default string used also during manual client creation: "Change me please!". Hoping this will trigger the owners to set a proper string.
Thanks @stlammel for the notice!
