### ISSUE TITLE
Invalid refresh token generated by a dynamically registered cient using the password flow 

### ISSUE THREAD

**Issue by aldbr** [indigo-iam/iam#575]
Hello,

I was doing some tests with the IAM API (using the `1.8.0` docker image provided in the documentation) when I found this "bug": I get an invalid refresh token from a dynamically registered client using the password flow.

Let's see an example. I want to create a new client with the `password` flow without having to interact with the web interface:

- `test_client.json`:
```json
{
  "redirect_uris": [
    "https://another.client.example/oidc"
  ],
  "client_name": "test-client",
  "contacts": [
    "admin@iam.test"
  ],
  "token_endpoint_auth_method": "client_secret_basic",
  "scope": "address phone openid email profile offline_access",
  "grant_types": [
    "refresh_token",
    "client_credentials",
    "authorization_code",
    "password"
  ],
  "response_types": [
    "code"
  ]
}
```

I cannot create it without an admin token because the `password` flow is restricted.
So, the only way of doing this is to get an admin token from the already existing `Password grant client` and then create `test-client`:

```bash
# Credentials that are already available when we start the docker container (you can get them from the web interface)
export INIT_CLIENT_ID=password-grant 
export INIT_CLIENT_SECRET=secret

# Get a token from the password-grant client with a password flow
curl -s \
  -u ${INIT_CLIENT_ID}:${INIT_CLIENT_SECRET} \
  -d username=admin \
  -d password=password \
  -d grant_type=password \
  http://localhost:8080/token \
  -o admin_init_token.json

export ADMIN_ACCESS_TOKEN=`cat admin_init_token.json | jq -r .'access_token'`

# Create test-client
curl -s \
  -X POST \
  -H "Content-Type:application/json" \
  -H "Authorization: Bearer ${ADMIN_ACCESS_TOKEN}" \
  -d @test_client.json \
  http://localhost:8080/iam/api/client-registration \
  -o result_test_client.json
```

This is the initial situation. From here, we can distinguish two different cases: getting a refresh token from `test-client` directly; interacting with the web interface and getting a refresh token from `test-client`.

- 1. getting a refresh token from `test-client` directly:

```bash
# Credentials of test-client
export TEST_CLIENT_ID=`cat result_test_client.json | jq -r .'client_id'`
export TEST_CLIENT_SECRET=`cat result_test_client.json | jq -r .'client_secret'`
  
# Get a token from test-client using the password flow
curl -s \
    -u ${TEST_CLIENT_ID}:${TEST_CLIENT_SECRET} \
    -d username=admin \
    -d password=password \
    -d grant_type=password \
    http://localhost:8080/token \
    -o admin_test_token.json

export ADMIN_REFRESH_TOKEN=`cat admin_test_token.json | jq -r .'refresh_token'`

# Try to get a token from test-client using the refresh_token flow
curl -s \
    -u ${TEST_CLIENT_ID}:${TEST_CLIENT_SECRET} \
    -d refresh_token=${ADMIN_REFRESH_TOKEN} \
    -d grant_type=refresh_token \
    http://localhost:8080/token
```
The result is:
```json
{
  "error":"invalid_token",
  "error_description":"Invalid refresh token: eyJhbGciOiJub25lIn0.eyJleHTiOjE2NzcyNDG0MDFsImp3aSI6ImQ2ZjA1YTI7LTIxNzktNGUxMi04OTcxLWZlMzZmODVjOTBlMiJ9."
}
```

- 2. interacting with the web interface and getting a refresh token from `test-client`:

  - Just go to the web interface, in the `Clients` section and select `test-client`.
  - Click on the `Save Client` button and rerun comands defined in `i.`.

The result is valid this time.

The simple act of clicking on the `Save Client` button changes the validity of the refresh token.
Do you know why?

I compared the `test-client` configuration before and after I click on the `Save Client` button to get further details.
As you can see, the `refresh_token_validity_seconds` field disappears after clicking on the `Save Client` button.

- Before:
```json
{
  "client_id": "27cbad49-7885-4636-ad50-18277ef9c9dc",
  "client_secret": "AJnBzbJIejFyk_9pXoQzQ-hZrnkTyFgl_1vzj-wsPIcmU3-y2i1hjo8HjsPBkIu7E3Qyep-47yIobO6itQVUdtk",
  "client_name": "test-client",
  "redirect_uris": [
    "https://another.client.example/oidc"
  ],
  "contacts": [
    "admin@iam.test"
  ],
  "grant_types": [
    "client_credentials",
    "authorization_code",
    "password",
    "refresh_token"
  ],
  "response_types": [
    "code"
  ],
  "token_endpoint_auth_method": "client_secret_basic",
  "scope": "address phone openid profile offline_access email",
  "access_token_validity_seconds": 3600,
  "refresh_token_validity_seconds": 0,
  "id_token_validity_seconds": 600,
  "device_code_validity_seconds": 600,
  "reuse_refresh_token": true,
  "dynamically_registered": true,
  "allow_introspection": true,
  "clear_access_tokens_on_refresh": true,
  "require_auth_time": false,
  "registration_client_uri": "http://localhost:8080/iam/api/client-registration/27cbad49-7885-4636-ad50-18277ef9c9dc",
  "created_at": 1677246350509
}
```

- After:
```json
{
  "client_id": "27cbad49-7885-4636-ad50-18277ef9c9dc",
  "client_secret": "AJnBzbJIejFyk_9pXoQzQ-hZrnkTyFgl_1vzj-wsPIcmU3-y2i1hjo8HjsPBkIu7E3Qyep-47yIobO6itQVUdtk",
  "client_name": "test-client",
  "redirect_uris": [
    "https://another.client.example/oidc"
  ],
  "contacts": [
    "admin@iam.test"
  ],
  "grant_types": [
    "client_credentials",
    "authorization_code",
    "password",
    "refresh_token"
  ],
  "response_types": [
    "code"
  ],
  "token_endpoint_auth_method": "client_secret_basic",
  "scope": "address phone openid profile offline_access email",
  "access_token_validity_seconds": 3600,
  "id_token_validity_seconds": 600,
  "device_code_validity_seconds": 600,
  "reuse_refresh_token": true,
  "dynamically_registered": true,
  "allow_introspection": true,
  "clear_access_tokens_on_refresh": true,
  "require_auth_time": false,
  "registration_client_uri": "http://localhost:8080/iam/api/client-registration/27cbad49-7885-4636-ad50-18277ef9c9dc",
  "created_at": 1677246350509
}
```

Thanks

**Comment by rmiccoli** [comment]
Hi, the problem stems from this [check](https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/java/it/infn/mw/iam/api/client/service/DefaultClientDefaultsService.java#L81). Since your client has "client credentials" among the grant types, when the client is dynamically registered, the default refresh token validity is set to 0 (expiration=current timestamp). By updating the client (clicking on Save Client button) the refresh token validity becomes null (=infinity) and then the token request is successful.

So, if you remove `client_credentials` from grant_types, you should no longer get that error!

**Comment by aldbr** [comment]
> Since your client has "client credentials" among the grant types, when the client is dynamically registered, the default refresh token validity is set to 0 (expiration=current timestamp). By updating the client (clicking on Save Client button) the refresh token validity becomes null (=infinity) and then the token request is successful.

Alright, thanks for the details.
Is it an expected feature? If yes, just out of curiosity, why does it work this way?

> So, if you remove client_credentials from grant_types, you should no longer get that error!

Seems like I can create the client without the `client_credentials` flow, and then update it with `grant_type=client_credentials` and `refresh_token_validity_seconds=X`.
It is a bit cumbersome, but if necessary, I can live with it.

**Comment by rmiccoli** [comment]
No, I was actually surprised when I discovered it and I would think it was a bug.
I suggested an workaround for the time being but we are working on solving the issue.

**Comment by rmiccoli** [comment]
PR #582
