### ISSUE TITLE
Remember IDP selection

### ISSUE THREAD

**Issue by dmichelotto** [indigo-iam/iam#59]
Great work IAM team.

If I can suggest a feature, it could be nice if when I'm using SAML credential after the first IDP selection the WAYF form remember my selection.

In my WAYF I used a drop down menu that permits users to select one of the following options: 
- 'Do not remember'
- 'Remember for session'
- 'Remember for a week'

The selection of an option simply set a browser cookie with the duration.

Best regards.
Diego

<img width="845" alt="schermata 2016-10-20 alle 14 51 05" src="https://cloud.githubusercontent.com/assets/1177985/19560411/b0e8856a-96d4-11e6-83b0-0829b5cdf0e1.png">

**Comment by dmichelotto** [comment]
Great work.

**Comment by andreaceccanti** [comment]
thanks!
