### ISSUE TITLE
Can't remove authentication from a client

### ISSUE THREAD

**Issue by chaen** [indigo-iam/iam#599]
If you select `Client secret over HTTP basic authentication` and save on a client, the basic auth works fine.
But then, if I tick the ` No authentication ` bullet again, the basic auth is still required. 
How do I get rid of that ? 
Thanks

**Comment by rmiccoli** [comment]
Which type of authorization flow are you using?

**Comment by chrisburr** [comment]
Authentication code with PKCE

**Comment by federicaagostini** [comment]
PR #676
