### ISSUE TITLE
Cross Site Scripting security issue reported by SLAC security

### ISSUE THREAD

**Issue by wguanicedew** [indigo-iam/iam#611]
A Cross-Site Scripting (XSS) attack is a type of attack in which a malicious script is injected into an otherwise benign and trusted web site.
An XSS attack occurs when an attacker uses a web application to send malicious code, generally in the form of a browser side script, to a different end user. Flaws that allow these attacks to succeed are widespread and occur anywhere a web application uses input from a user within the output it generates without validating or encoding it.
HTML injection is similar to XSS but inserts HTML content into the web page using HTML tags like <iframe> or <input> instead of <script> tags. Typically, a page vulnerable to XSS is also vulnerable to HTMLi.
Reflected XSS describes the attack technique where the value is passed via the browser either through a malicious URL or link and is not stored on the web server.

Summary
The web application hosted at https://rubin-panda-iam-dev.slac.stanford.edu/ (https://rubin-panda-iam- dev.slac.stanford.edu/) is vulnerable to Reflected Cross-Site Scripting (XSS) attacks at the /login endpoint via the externalAuthenticationError GET parameter.
Impact
An attacker can execute arbitrary JavaScript code on a victim's browser under the rubin-panda-iam- dev.slac.stanford.edu after such a user clicks a maliciously crafted link or visits an attacker-controlled website. This allows the attacker to compromise the victim user's account, allowing them to perform actions on the application as the victim user and view data available to the victim user.
Recommendation
Implement input validation to prevent HTML meta-characters from being reflected back to the client without first being properly encoded.

**Comment by federicaagostini** [comment]
Hi,

thank you for your report.
This is a known vulnerability which has been reported [here](https://github.com/indigo-iam/iam/security/advisories/GHSA-hp7f-pm3x-r465) (where a workaround is also suggested).

We are planning to fix it very soon in a dedicated release.

**Comment by enricovianello** [comment]
I'm deleting this issue because it's not safe to open a public issue about a vulnerability, but you'll receive an email with this update/comment so I can confirm you that next IAM 1.8.3 will contain the fix. Cheers
