### ISSUE TITLE
email and health end point(s)

### ISSUE THREAD

**Issue by ygrange** [indigo-iam/iam#614]
Heya,

I have an issue configuring mail (I set up a simple debug SMTP server for my test instance, which just prints all requests to STDOUT just to be able to play around a bit without the shenanigans of real emails being sent around and blocked by checks on the host name / IP).  I think I configured all the keys in the env correctly but even when running a simple netcat listening to this port: when I request a password reset link to be sent to a user, no communication whatsoever seems to happen to the SMTP server. Am I doing anything wrong here? I can telnet into the server without an issue. Those are the relevant config lines:
```
# SMTP server hostname
IAM_MAIL_HOST=debug_smtp

# SMTP server port
IAM_MAIL_PORT=25
```
(this is a docker-compose setup so the host debug_smtp is a container running said python script). I tried with and withoyt user credentials and with or without IAM_NOTIFICATION_ADMIN_ADDRESS / IAM_NOTIFICATION_FROM but neither seem to have any effect...

Then I tried looking at `/health/mail` or at `/health` which return a 404, then I found the commits moving those end points  (could you please update the docs on this?) , but `/actuator/health/mail` seems still not to work. So I am a bit in the dark here on what to try next.

**Comment by rmiccoli** [comment]
Hi,

the documentation has been already updated (see https://indigo-iam.github.io/v/v1.8.2/docs/reference/api/health_endpoints/#actuatorhealthmail). Make sure you have set the env variable `IAM_HEALTH_MAIL_PROBE_ENABLED=true` that enables the SMTP server check.

**Comment by federicaagostini** [comment]
Closing as the above suggestion should solve the issue: feel free to reopen it if this is not the case.
