### ISSUE TITLE
error 415 for user creation with post /scim/Users

### ISSUE THREAD

**Issue by sigau** [indigo-iam/iam#621]
Hi 
I am writing to seek assistance regarding an issue I encountered while attempting to transfer user data from another platform to our instance of Indigo IAM. Specifically, I am using the SCIM API to send the extracted user information to the "scim/Users" endpoint. However, I am consistently receiving an "Error 415" response, indicating that the request data format is not supported by the server.

Upon careful review of the documentation, I ensured that the "Content-Type" header is set to "application/json" as instructed. Despite this, the error persists.

Here is a relevant section of the script that triggers the error:

def CREATE_USER_CMD(nom,prenom,mail,username):
    GENERATE_TOKEN()
    headers = {"Content-Type": "application/json","Authorization": "Bearer %s" % token}
    todo = {"userName": f"{username}","name": {"givenName": f"{prenom}","familyName": f"{nom}","formatted": f"{prenom} {nom}"},"emails": [{"type": "work","value": f"{mail}","primary": True}]}
    api_url = f"{main_url}:/scim/Users/"
    response = requests.post(api_url, json=todo, headers=headers )
    print(response.status_code)

I would greatly appreciate your assistance in identifying the source of this issue. Could you kindly advise on any potential causes or suggest troubleshooting steps to resolve this error? Any guidance you can provide would be immensely helpful.

Thank you in advance for your time and support.

Best regards,
Gautier

**Comment by rmiccoli** [comment]
Hi,

I think the problem is the Content-Type which should be `application/scim+json;charset=UTF-8`. 
Could you please retry?

**Comment by sigau** [comment]
Hi !
it does work,
thank you!
