### ISSUE TITLE
API error since upgrade from 1.8.0 to 1.8.2p1

### ISSUE THREAD

**Issue by sigau** [indigo-iam/iam#627]
Hi 

Since last week, after upgrading from version 1.8.0 to 1.8.2p1, we have encountered errors with all APIs except for "/scim/Me". For example:

  -  "/iam/account/search" returns: {"error":"insufficient_scope","error_description":"Insufficient scope for this resource","scope":"iam:admin.read"}.
  -  "/scim/Users/" returns: {"error":"insufficient_scope","error_description":"Insufficient scope for this resource","scope":"scim:read"}.

However, when I checked the web interface, I found that all possible scopes are enabled. You can refer to the following image: 

![image](https://github.com/indigo-iam/iam/assets/44998219/e7c16842-1edd-4281-af00-e85d7aee3418)

Could this problem be introduced with the latest version?

Thank you in advance.
Gautier

**Comment by giacomini** [comment]
Hi Gautier.
1.8.2 introduced a change that is described in the [release notes](https://github.com/indigo-iam/iam/releases/tag/v1.8.2):
```
* Introduced new admin scopes in order to access IAM API endpoints https://github.com/indigo-iam/iam/pull/562

    Note: From this release, an administrator access token is not enough to have full access to IAM API endpoints. The added scopes (iam:admin.read and iam:admin.write) are now needed.
```
If you use `oidc-agent`, I think you have to re-run `oidc-gen` with the option `-m` so that the client knows about the new scopes that, as you show, are already assigned to the client on the dashboard.

**Comment by sigau** [comment]
I will try but this client have been create with oidc-gen -w after the update and all the scopes available are the following : 

The following scopes are supported: openid profile email address phone offline_access eduperson_scoped_affiliation eduperson_entitlement eduperson_assurance entitlements 

Do I have to add them everytime we create a new client ?

**Comment by sigau** [comment]
So, it works after performing oidc-gen -m. However, even when I create a new client, I still have to add them manually, which is not very convenient. Nevertheless, it does work

**Comment by giacomini** [comment]
Those scopes are quite powerful (and "restricted", in IAM terms). A bit of inconvenience can save from much pain.

I'll close the issue, but if you have ideas on how to simplify the workflow, we can open another discussion, involving also the developes of oidc-agent.
