### ISSUE TITLE
The `exp` claim should always appear in the JWT 

### ISSUE THREAD

**Issue by federicaagostini** [indigo-iam/iam#648]
According with [RFC 9068](https://datatracker.ietf.org/doc/html/rfc9068#name-data-structure), the `exp` claim of the JWT (indicating the expiration time) should appear in the token.

In IAM, when one sets the access token lifetime as infinite (value equal to 0) the `exp` claim does not appear in the AT.

We should not allow users to set an infinite lifetime of the token. Suggestion on the max lifetime one can set for an AT is commented [here](https://github.com/indigo-iam/iam/issues/545#issuecomment-1708264590).

**Comment by federicaagostini** [comment]
Solved in MitreID, with commit [0c64dc6](https://github.com/indigo-iam/OpenID-Connect-Java-Spring-Server/commit/0c64dc68864dc317705443fe6d1876cda6d47d74).

**Comment by giacomini** [comment]
Just for the record, the `exp` claim *must* appear in the token.
