### ISSUE TITLE
Allow to control button ordering on the login page

### ISSUE THREAD

**Issue by jouvin** [indigo-iam/iam#658]
In v1.8.2, button order on the login page is always: OIDC, SAML, Local accounts (if enabled and hidden_with_link is selected). Depending on instances, it may be desirable to have SAML first and OIDC second. For example in one of our instance, we'd like to encourage users to use eduGAIN and if it is not possible, to use ORCID. Having ORCID first may have the risk of achieving the opposite... Just allowing to say SAML_BUTTON_FIRST (as I think you cannot have several SAML buttons) is enough for this use case. We can see later if there is a need to control the ordering of OIDC buttons (where you can easily have several).

**Comment by federicaagostini** [comment]
PR https://github.com/indigo-iam/iam/pull/668
