### ISSUE TITLE
Incorrect SAML Recipient Endpoint

### ISSUE THREAD

**Issue by bl000m** [indigo-iam/iam#667]
Hi,

I created a Service Provider in Renater for testing an instance (https://fits-indigo-iam-test.in2p3.fr/login). I configured the ACS URL to end with ".../saml/sso" with an index of 0. I followed the instructions in the Indigo IAM documentation, but I can't seem to find that documentation anymore.

When I select "GIP RENATER - IdP de test" as the Identity Provider (IdP) and try to authenticate using the "etudiant1" test account, I am redirected back to the IAM instance login page with the following error: "IdP External authentication error. Incoming SAML message is invalid."

Upon checking the Indigo IAM logs, I discovered a mismatch between what I set as the Assertion endpoint in the Renater test SP configuration (https://...) and the recipient endpoint (http://...):

`SAML message intended destination endpoint 'https://fits-indigo-iam-test.in2p3.fr/saml/SSO' did not match the recipient endpoint 'http://fits-indigo-iam-test.in2p3.fr/saml/SSO'.`

The issue I'm facing is that I don't know how to change the recipient endpoint, and the page in the Indigo IAM documentation that I initially used for configuration no longer appears to contain any references to the ACS URL ".../saml/sso." and "index = 0":  https://indigo-iam.github.io/v/v1.7.2/docs/reference/configuration/external-authentication/saml/

Could you please help me understand how to resolve this?

**Comment by rmiccoli** [comment]
Hi @bl000m,

have you set the env variable `IAM_FORWARD_HEADERS_STRATEGY=native` in your configuration file?

**Comment by bl000m** [comment]
Hi @rmiccoli ,

thank you, it was exactly that (it was set to none) !
