### ISSUE TITLE
Single-shot refesh-tokens from urn:ietf:params:oauth:grant-type:token-exchange 

### ISSUE THREAD

**Issue by murrayc3** [indigo-iam/iam#707]
Dear IAM experts,

Our FTS services at CERN have observed that refresh tokens given via the urn:ietf:params:oauth:grant-type:token-exchange grant type are single-shot.  Whilst the FTS software handles this, the overall WLCG protocol is very fragile.  If an FTS server loses track of a refresh token then it can no longer refresh the associated access token.

Can IAM be configured to exchange access-tokens for refresh-tokens that can be used multiple times until their expiration timestamp?

Regards,

Steven Murray - FTS Service Manager at CERN

**Comment by rmiccoli** [comment]
Hi, there exists an option to reuse the refresh tokens until the expiry date. If you go to the _Tokens_ section of the client configuration in the IAM dashboard, you can easily change it.

**Comment by murrayc3** [comment]
Hi,
This is great news!  I will relay the information to the https://atlas-auth.web.cern.ch/ service here at CERN.
Regards,
Steve

**Comment by federicaagostini** [comment]
Closing the issue as the _Reuse refresh token_ box checked should have been fixed the issue.
