### ISSUE TITLE
IAM serves a 404 when the Logout Button is Selected

### ISSUE THREAD

**Issue by norealroots** [indigo-iam/iam#709]
Hi!
I am aware that this is likely a configuration error rather than a bug, however I cannot seem to work out the cause of this.
For our SKA prototyping IAM instance, https://ska-iam.stfc.ac.uk, when a user attempts to press the logout button, a 404 error is returned for the URL https://ska-iam.stfc.ac.uk/logout. This means that the user is not actually logged out, and instead just has to let their session expire.
I've gone over my config, and can see no obvious differences between this instance and iris-iam.stfc.ac.uk, which sees the expected behavior for logout.
I am happy to share config/nginx files for sanity checking, if useful.
Thanks!

**Comment by norealroots** [comment]
Hi,
Could I nudge this please?
Thanks,
Tom

**Comment by federicaagostini** [comment]
Hi Tom, yes sorry, we also never experienced this issue.

If you can share your nginx file and eventually application*.yml it would be great.

**Comment by norealroots** [comment]
I'll email those over to you tomorrow.

**Comment by norealroots** [comment]
An update...
> Hi Tom,
> I've realized that the ska-iam.stfc.ac.uk.conf file contains the directive
> ```
>    location /logo {
>      index skao_pictorial.png;
>    }
> ```
> which also matches /logout (like this it works as prefix string matching).
> For exact string matching you could use something like "`location = /logo`".
> Not sure it is the problem, but could you give a try?
> The rest of the configuration looks OK to me.
> Best,
> Federica

🤦‍♂️

Moving the logo file from `/logo` to `/skao_pictorial` in the nginx config fixed the issue. 
Thanks for the help @federicaagostini!
