### ISSUE TITLE
Missing AUP email notifications

### ISSUE THREAD

**Issue by vokac** [indigo-iam/iam#732]
There are more [VOMS-Admin notifications](https://github.com/italiangrid/voms-admin-server/tree/master/voms-admin-server/src/main/resources/templates) then those currently available in [IAM mail templates](https://github.com/indigo-iam/iam/tree/master/iam-login-service/src/main/resources/email-templates). This needs to be fixed before legacy VOMS server can be replaced with IAM
* AUP reminder
* AUP expiration
* account suspension(?)
* account restoration(?)

**Comment by maarten-litmaath** [comment]
Hi all,
at least the ATLAS VO admins would also want to be notified on:
- account suspension;
- account restoration (probably).
Ideally, the exact notification subscriptions would be configurable,
but I could imagine that being made possible in a second phase...

**Comment by rmiccoli** [comment]
Splitting issues and PRs by topic, AUP and account suspension/restoration.
See also https://github.com/indigo-iam/iam/issues/786
