### ISSUE TITLE
The jwk endpoint should honour the "application/jwk+json" content-type request

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#74]
As hinted by Bas, the IAM jwk endpoint should be able to honour content-type request for "application/jwk+json" for keys, as stated in https://tools.ietf.org/html/rfc7517 , section 8.5.1

**Comment by marcocaberletti** [comment]
Hi,
reading the RFC I understand that the content types "jwk+json" and "jwk-set+json" are used
only if the returned response contains non-public key material (see https://tools.ietf.org/html/rfc7517#section-7).
Currently, IAM exposes only the public part of the JWK, then these extensions seem not necessary.
Could you confirm this?

**Comment by bwegh** [comment]
@marcocaberletti 
I understand that it MUST be set in the cases mentioned by you, still the chapter of media type registration Section 8.5.1 (https://tools.ietf.org/html/rfc7517#section-8.5) points out that the jwk+json is registered '[...] to indicate that the content is a JWK', and that`s what it is.
