### ISSUE TITLE
Potential ARM support for images

### ISSUE THREAD

**Issue by DonaldChung-HK** [indigo-iam/iam#751]
## Description
I was wondering if it would be possible for IAM to support ARM64 architecture by compiling docker image for ARM-based CPU

## Possible reason for the issue
For users who wish to run the indigoiam on a public cloud, it could deliver a significant cost savings.
- Cloud ARM CPUs is optimal platform for applications with low resource requirements with potential period of burst needed during high demand period, these burst capacity could be 7x higher compare to traditional x86 CPU. 
- Thus, it could offer cost savings for user by reserving cheaper flavours.
- Also, it offers flexibility for the IAM community to run this application on a smaller scale using low-powered consumer ARM parts and allow the IAM to reach a wider communities.
## Task or fixes
I already have some ARM based container running. Since IAM is an spring application so the JVM already allow applications to run without developer worrying about the physical parts. Thus I anticipate the work for the following:
- Change the underlying eclipse-temurin image (the JVM runtime)
- Change tini so that it is based on the architecture 
https://github.com/DonaldChung-HK/iam/commit/ba21797df68ef9c6266a84c392e32700cf5df17f 
- Use docker buildx virtualisation to build the ARM image
https://github.com/DonaldChung-HK/iam/commit/27ee2f0be057fa28111211ecb29b8bbe7364724c
    - Or set up new Github actions workflow
- Confirm that the associated test for the image are adapted to ARM based environment.
    - It shouldn't affect the Java application so probably just the post build checks

**Comment by enricovianello** [comment]
@DonaldChung-HK 
The first release candidate for next IAM v1.9.0 release is out and it has been built also for arm64 platform 👍 
https://hub.docker.com/layers/indigoiam/iam-login-service/v1.9.0.rc.20240606/images/sha256-6c5539d54efd52ea2bee08cf2f41c761fb5576a5f0897e1e2061e0ae5eda80a3?context=explore
