### ISSUE TITLE
Newly registered users are not enforced to sign the AUP

### ISSUE THREAD

**Issue by rmiccoli** [indigo-iam/iam#760]
They can log in the first time without signing the AUP (if defined in IAM).
In fact, the aup signature time is the same as the time when the registration request was submitted.

Is this the same bug @maarten-litmaath found a few days ago?

**Comment by maarten-litmaath** [comment]
Hi all,
the registration form says something like "by proceeding, you agree to the AUP",
for which a link is provided: I suppose we can decide it is good enough (for now)?

It would then be OK to set the AUP signature time to the time of the registration...

**Comment by rmiccoli** [comment]
You are right, I missed that sentence. 
Then I think it is a deliberate behaviour and we can close the issue for now.
