### ISSUE TITLE
emails from IAM - improve tagging and filtering

### ISSUE THREAD

**Issue by AleDiGGi** [indigo-iam/iam#785]
Ciao, now that IAM will be in full production also as replacement of VOMS-Admin, it might be useful to have emails with clear subject and sender to make easier the tagging/labelling in the email clients.
E.g. sender could be, instead of no-reply (Unmonitored address) <no-reply@cern.ch>, something like "iam-xxx@cern.ch"
Subject could be, instead of e.g. "New membership request for group atlas/usatlas " something like "[IAM ATLAS] New membership request for group atlas/usatlas
These are obviously minor improvements, low priority but should be somehow simple to be implemented and could ease the life of the VO Admins.
Ciao

**Comment by balciiberk** [comment]
The sender can already be configured but AFAIU the subject is hardcoded and cannot be configured currently.

**Comment by rmiccoli** [comment]
As a first approach we thought of adding in the subject (hardcoded) `[<organisation_name> IAM] ...`, e.g. `[atlas IAM]`
