### ISSUE TITLE
Migrate scope management to IAM dashboard

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#85]
Currently the IAM leverages the MitreID connect dashboard for scope management.
The scope management frontend code should be migrated to the IAM angular dashboard, in order
to provide a more consistent web application.

# Useful references

- [System scope API documentation](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/API#system-scopes)
- [Current Mitre Dashboard code](https://github.com/indigo-iam/iam/blob/master/iam-login-service/src/main/webapp/resources/js)

**Comment by enricovianello** [comment]
Moved development into [scope-management](https://github.com/indigo-iam/iam/tree/scope-management) branch.
