### ISSUE TITLE
AUP signature endpoint does not read the request body

### ISSUE THREAD

**Issue by federicaagostini** [indigo-iam/iam#852]
When one wants to set the AUP signature time by API with 

```
PATCH /iam/aup/signature/<account-id>
```

with some body, like

```
{
  "signatureTime": "2023-04-27T11:35:20.000+02:00"
}
```

 IAM always sets the signature time to the current date regardless of _signatureTime_ parameter.

The signature time endpoint was introduced correctly with PR https://github.com/indigo-iam/iam/pull/608, but then the behavior was modified (by mistake?) by PR https://github.com/indigo-iam/iam/pull/777.

**Comment by enricovianello** [comment]
Fixed within IAM v1.10.2
