### ISSUE TITLE
Protect against spurious HEAD requests

### ISSUE THREAD

**Issue by giacomini** [indigo-iam/iam#862]
Some tools (e.g. Outlook) try to protect their users from phishing URLs performing a HEAD request to that URL first. In case of IAM, this happens at least for the user verification email, which contains a link to the `/registration/verify` endpoint, causing a 401. Though in this case that response is practically harmless, it's better to manage those requests properly.

Other such endpoints may exist.

**Comment by vokac** [comment]
Would it be possible to increase priority for this issue, this is getting really annoying ... I would even recommend hotfix in case regular IAM release doesn't come out very soon.
