### ISSUE TITLE
Null Expiration tokens not removed

### ISSUE THREAD

**Issue by DonaldChung-HK** [indigo-iam/iam#892]
Hi,

I found in the DB that some access token or refresh token with `NULL` as expiration are not removed but I think that IAM switched to using 0 for non-expiring tokens. I was wondering if they are needed and do they pose a security threat.

Thanks.

**Comment by rmiccoli** [comment]
Hi @DonaldChung-HK, you're right that 0 is used for non-expiring tokens but in the database the expiration is saved as NULL.

**Comment by rmiccoli** [comment]
Regarding the access token table, there are some tokens with no expiry date called **registration access tokens** (RAT) that are saved in the db table but don't appear in the IAM dashboard. They're generated when the client is dynamically registered via the command line or via oidc-agent (newer versions of oidc-agent no longer support RATs). They're used to retrieve the client configuration later and also to update or delete the client.

**Comment by DonaldChung-HK** [comment]
Hi @rmiccoli, Thanks for the answer, I will close this as resolved.
